<?php
die('111');
ob_start();
session_start();
ini_set('display_errors',1);
define('libs_path','libs/');
require_once(libs_path.'gfconfig.php');
require_once(libs_path.'gfinit.php');
require_once(libs_path.'gffunc.php');
require_once(libs_path.'cls.mysql.php');
define('ISHOME',true);

$arr = new array();
$arr['code'] = '';
$arr['name'] = '';
$arr['unit'] = '';
$arr['cost'] = '';
$arr['price'] = '';
$arr['alert_quantity'] = '';
$arr['image'] = '';
$arr['category_id'] = '';
$arr['subcategory_id'] = '';
$arr['cf1'] = '';
$arr['cf2'] = '';
$arr['cf3'] = '';
$arr['cf4'] = '';
$arr['cf5'] = '';
$arr['cf6'] = '';
$arr['quantity'] = '';
$arr['tax_rate'] = '';
$arr['track_quantity'] = '';
$arr['details'] = '';
$arr['warehouse'] = '';
$arr['barcode_symbology'] = '';
$arr['file'] = '';
$arr['product_details'] = '';
$arr['tax_method'] = '';
$arr['type'] = '';
$arr['supplier1'] = '';
$arr['supplier1price'] = '';
$arr['supplier2'] = '';
$arr['supplier2price'] = '';
$arr['supplier3'] = '';
$arr['supplier3price'] = '';
$arr['supplier4'] = '';
$arr['supplier4price'] = '';
$arr['supplier5'] = '';
$arr['supplier5price'] = '';
$arr['promotion'] = '';
$arr['promo_price'] = '';
$arr['start_date'] = '';
$arr['end_date'] = '';
$arr['supplier1_part_no'] = '';
$arr['supplier2_part_no'] = '';
$arr['supplier3_part_no'] = '';
$arr['supplier4_part_no'] = '';
$arr['supplier5_part_no'] = '';
$arr['sale_unit'] = '';
$arr['purchase_unit'] = '';
$arr['brand'] = '';
$arr['slug'] = '';
$arr['featured'] = '';
$arr['weight'] = '';
$arr['hsn_code'] = '';
$arr['views'] = '';
$arr['hide'] = '';
$arr['second_name'] = '';
$arr['hide_pos'] = '';

SysAdd('sma_products', $arr);
?>